service: workouts

provider:
  name: aws
  stage: dev
  runtime: python2.7
  environment:
    EVENT_STORE_TABLE: ${self:service}-${opt:stage, self:provider.stage}-event-store
    VIEW_STORE_TABLE: ${self:service}-${opt:stage, self:provider.stage}-view-store
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: 
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.EVENT_STORE_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.VIEW_STORE_TABLE}"

functions:
  getnextworkout:
    handler: handler.get_next_workout
    events:
      - http:
          path: workouts
          method: get
          cors: true
  saveexercise:
    handler: handler.save_exercise
    events:
      - http:
          path: workouts
          method: post
          cors: true
  projectexercise:
    handler: handler.project_exercise
    events:
      - stream:
        type: dynamodb
        arn:
          Fn::GetAtt:
            - EventStoreDynamoDbTable
            - StreamArn

resources:
  Resources:
    EventStoreDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: ExerciseName
            AttributeType: S
          -
            AttributeName: DateOfExercise
            AttributeType: S
        KeySchema:
          -
            AttributeName: ExerciseName
            KeyType: HASH
          -
            AttributeName: DateOfExercise
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TableName: ${self:provider.environment.EVENT_STORE_TABLE}
    ViewStoreDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: ExerciseName
            AttributeType: S
        KeySchema:
          -
            AttributeName: ExerciseName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.VIEW_STORE_TABLE}